[2021-11-27 06:18:10,355] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: elt.upload scheduled__2021-11-26T23:17:00+00:00 [queued]>
[2021-11-27 06:18:10,360] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: elt.upload scheduled__2021-11-26T23:17:00+00:00 [queued]>
[2021-11-27 06:18:10,360] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 06:18:10,360] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-27 06:18:10,360] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 06:18:10,368] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): upload> on 2021-11-26 23:17:00+00:00
[2021-11-27 06:18:10,369] {standard_task_runner.py:52} INFO - Started process 2312 to run task
[2021-11-27 06:18:10,374] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'elt', 'upload', 'scheduled__2021-11-26T23:17:00+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/processing.py', '--cfg-path', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmp4bkjvobs', '--error-file', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmpw1s3z68a']
[2021-11-27 06:18:10,376] {standard_task_runner.py:77} INFO - Job 42: Subtask upload
[2021-11-27 06:18:10,403] {logging_mixin.py:109} INFO - Running <TaskInstance: elt.upload scheduled__2021-11-26T23:17:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-11-27 06:18:10,430] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=elt
AIRFLOW_CTX_TASK_ID=upload
AIRFLOW_CTX_EXECUTION_DATE=2021-11-26T23:17:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-26T23:17:00+00:00
[2021-11-27 06:18:10,431] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T
[2021-11-27 06:18:10,432] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/Home/Airflow/tasks/cleaning.py /Users/Home/Airflow/output worldbank']
[2021-11-27 06:18:10,437] {subprocess.py:85} INFO - Output:
[2021-11-27 06:18:10,485] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_SH.STA.MMRT_DS2_en_csv_v2_3159367.csv: No such file or directory
[2021-11-27 06:18:10,490] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_SH.DYN.MORT_DS2_en_csv_v2_3162033.csv: No such file or directory
[2021-11-27 06:18:10,496] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_DT.ODA.ODAT.GN.ZS_DS2_en_csv_v2_3161196.csv: No such file or directory
[2021-11-27 06:18:10,502] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_SH.TBS.INCD_DS2_en_csv_v2_3165510.csv: No such file or directory
[2021-11-27 06:18:10,508] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_DT.ODA.ODAT.XP.ZS_DS2_en_csv_v2_3164297.csv: No such file or directory
[2021-11-27 06:18:10,514] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_DT.ODA.ODAT.GI.ZS_DS2_en_csv_v2_3164289.csv: No such file or directory
[2021-11-27 06:18:10,520] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_SI.DST.FRST.20_DS2_en_csv_v2_3165548.csv: No such file or directory
[2021-11-27 06:18:10,521] {subprocess.py:89} INFO - API_SH.STA.MMRT_DS2_en_csv_v2_3159367.csv
[2021-11-27 06:18:10,521] {subprocess.py:89} INFO - API_SH.DYN.MORT_DS2_en_csv_v2_3162033.csv
[2021-11-27 06:18:10,521] {subprocess.py:89} INFO - API_DT.ODA.ODAT.GN.ZS_DS2_en_csv_v2_3161196.csv
[2021-11-27 06:18:10,521] {subprocess.py:89} INFO - API_SH.TBS.INCD_DS2_en_csv_v2_3165510.csv
[2021-11-27 06:18:10,521] {subprocess.py:89} INFO - API_DT.ODA.ODAT.XP.ZS_DS2_en_csv_v2_3164297.csv
[2021-11-27 06:18:10,522] {subprocess.py:89} INFO - API_DT.ODA.ODAT.GI.ZS_DS2_en_csv_v2_3164289.csv
[2021-11-27 06:18:10,522] {subprocess.py:89} INFO - API_SI.DST.FRST.20_DS2_en_csv_v2_3165548.csv
[2021-11-27 06:18:10,527] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-27 06:18:10,545] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=elt, task_id=upload, execution_date=20211126T231700, start_date=20211126T231810, end_date=20211126T231810
[2021-11-27 06:18:10,560] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-27 06:18:10,575] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
