[2021-11-27 02:13:07,884] {taskinstance.py:1025} INFO - Dependencies not met for <TaskInstance: daily-scraping.scraping manual__2021-11-26T19:12:44.754876+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2021-11-26T19:13:07.884323+00:00 and task will be retried at 2021-11-26T19:18:04.576064+00:00.
[2021-11-27 02:13:07,889] {local_task_job.py:99} INFO - Task is not able to be run
