[2021-11-27 09:47:11,739] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: elt.upload scheduled__2021-11-27T02:46:00+00:00 [queued]>
[2021-11-27 09:47:11,765] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: elt.upload scheduled__2021-11-27T02:46:00+00:00 [queued]>
[2021-11-27 09:47:11,765] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 09:47:11,765] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2021-11-27 09:47:11,765] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-27 09:47:11,772] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): upload> on 2021-11-27 02:46:00+00:00
[2021-11-27 09:47:11,774] {standard_task_runner.py:52} INFO - Started process 4834 to run task
[2021-11-27 09:47:11,779] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'elt', 'upload', 'scheduled__2021-11-27T02:46:00+00:00', '--job-id', '222', '--raw', '--subdir', 'DAGS_FOLDER/processing.py', '--cfg-path', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmpysry6tjv', '--error-file', '/var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T/tmpp2x2h8hk']
[2021-11-27 09:47:11,781] {standard_task_runner.py:77} INFO - Job 222: Subtask upload
[2021-11-27 09:47:11,810] {logging_mixin.py:109} INFO - Running <TaskInstance: elt.upload scheduled__2021-11-27T02:46:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2021-11-27 09:47:11,848] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=elt
AIRFLOW_CTX_TASK_ID=upload
AIRFLOW_CTX_EXECUTION_DATE=2021-11-27T02:46:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-27T02:46:00+00:00
[2021-11-27 09:47:11,849] {subprocess.py:62} INFO - Tmp dir root location: 
 /var/folders/hj/g8v71bv11_gb814qbbwch8zc0000gn/T
[2021-11-27 09:47:11,850] {subprocess.py:74} INFO - Running command: ['bash', '-c', '/Users/Home/Airflow/tasks/cleaning.py /Users/Home/Airflow/output worldbank']
[2021-11-27 09:47:11,860] {subprocess.py:85} INFO - Output:
[2021-11-27 09:47:11,921] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_NV.AGR.TOTL.ZS_DS2_en_csv_v2_3160861.csv: No such file or directory
[2021-11-27 09:47:11,927] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.LND.ARBL.ZS_DS2_en_csv_v2_3161161.csv: No such file or directory
[2021-11-27 09:47:11,933] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.LND.TRAC.ZS_DS2_en_csv_v2_3163924.csv: No such file or directory
[2021-11-27 09:47:11,940] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.YLD.CREL.KG_DS2_en_csv_v2_3163929.csv: No such file or directory
[2021-11-27 09:47:11,946] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_SL.AGR.EMPL.FE.ZS_DS2_en_csv_v2_3165570.csv: No such file or directory
[2021-11-27 09:47:11,952] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.PRD.CROP.XD_DS2_en_csv_v2_3159593.csv: No such file or directory
[2021-11-27 09:47:11,959] {subprocess.py:89} INFO - rm: /Users/Home/Airflow/output/*API_AG.LND.ARBL.HA.PC_DS2_en_csv_v2_3163892.csv: No such file or directory
[2021-11-27 09:47:11,959] {subprocess.py:89} INFO - API_NV.AGR.TOTL.ZS_DS2_en_csv_v2_3160861.csv
[2021-11-27 09:47:11,959] {subprocess.py:89} INFO - API_AG.LND.ARBL.ZS_DS2_en_csv_v2_3161161.csv
[2021-11-27 09:47:11,959] {subprocess.py:89} INFO - API_AG.LND.TRAC.ZS_DS2_en_csv_v2_3163924.csv
[2021-11-27 09:47:11,960] {subprocess.py:89} INFO - API_AG.YLD.CREL.KG_DS2_en_csv_v2_3163929.csv
[2021-11-27 09:47:11,960] {subprocess.py:89} INFO - API_SL.AGR.EMPL.FE.ZS_DS2_en_csv_v2_3165570.csv
[2021-11-27 09:47:11,960] {subprocess.py:89} INFO - API_AG.PRD.CROP.XD_DS2_en_csv_v2_3159593.csv
[2021-11-27 09:47:11,961] {subprocess.py:89} INFO - API_AG.LND.ARBL.HA.PC_DS2_en_csv_v2_3163892.csv
[2021-11-27 09:47:11,967] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-27 09:47:11,985] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=elt, task_id=upload, execution_date=20211127T024600, start_date=20211127T024711, end_date=20211127T024711
[2021-11-27 09:47:12,006] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-27 09:47:12,027] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
